<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "links".
 *
 * @property string $link
 * @property string $added
 * @property integer $group
 * @property string $youtubeID
 */
class Link extends \yii\db\ActiveRecord
{

    public function getYoutubeID(){
        return preg_replace('/(.*)\?v=/', '', $this->link);
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'links';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['added', 'group'], 'safe'],
            [['link'], 'required'],
            [['youtubeID'], 'string', 'max' =>  11],
            [['link'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'link' => 'Link',
            'added' => 'Added',
            'group' => 'Group',
            'youtubeID' =>  'youtubeID'
        ];
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord || empty($this->youtubeID)){
            $this->youtubeID = $this->getYoutubeID();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
